conn = database('iLS', '', '');
 setdbprefs('DataReturnFormat','numeric');
str = ['select subid,age,NTrials  from AllData where FB = 0 AND NTrials = 32;']
x = fetch(conn,str);

[Subid I J] = unique(x(:,1));
Age = x(I,2);
NSub = length(Subid);

NTrials = zeros(NSub,1);
for i = 1:max(J)
    NTrials(i) = sum(x(find(J==i),3));
end

str = ['select sex  from AllData ;']
setdbprefs('DataReturnFormat','cellarray');
x = fetch(conn,str);
Sex = x(I);
SumData = zeros(28,2,NSub);
for i = 1:NSub
    SumData(:,:,i) = FindAllData(Subid(i));
end

% Find the number of trials
setdbprefs('DataReturnFormat','numeric');

str = ['select sum(NTrials) from AllData where FB=0 AND NTrials = 32 group by subid;'];
NTrials = fetch(conn,str);


 Names = {'L2POSN1POS' ...
 'L2POSN1NEG' ...
 'L2POSN2POS' ...
 'L2POSN2NEG' ...
 'L2NEGN1POS' ...
 'L2NEGN1NEG' ...
 'L2NEGN2POS' ...
 'L2NEGN2NEG' ...
 'L6POSN1POS' ...
 'L6POSN1NEG' ...
 'L6POSN2POS' ...
 'L6POSN2NEG' ...
 'L6NEGN1POS' ...
 'L6NEGN1NEG' ...
 'L6NEGN2POS' ...
 'L6NEGN2NEG'...
 'L2POSN1'...
 'L2POSN2'...
 'L2NEGN1'...
 'L2NEGN2'...
 'L6POSN1'...
 'L6POSN2'...
 'L6NEGN1'...
 'L6NEGN2'...
 'L2N1'...
 'L2N2'...
 'L6N1'...
 'L6N2'}


OutFileName = ['iLS_' date '.csv'];
fid = fopen(OutFileName,'w')
%fid = 1;
fprintf(fid,'subid,Age,Sex,NTrials,');
for i = 1:length(Names)
     fprintf(fid,'%s_Acc,',Names{i});
end
for i = 1:length(Names)
     fprintf(fid,'%s_mRT,',Names{i});
end
fprintf(fid,'\n');

for i = 1:NSub
    fprintf(fid,'%d,%d,%s,',Subid(i),Age(i),Sex{i},NTrials(i));
    fprintf(fid,'%0.3f,',SumData(:,1,i)');
    fprintf(fid,'%0.3f,',SumData(:,2,i)');
    fprintf(fid,'\n');
end
fclose(fid)
fprintf(1,'Data written to:\n\t%s\n',OutFileName)
